export default String.raw`<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Emberfall 後台</title><style>
:root{color-scheme:dark}body{margin:0;background:#0e1420;color:#dbe8fa;font:15px system-ui}main{max-width:1300px;margin:auto;padding:28px}h1{color:#f2bb75}button,input,select{font:inherit;padding:10px;border-radius:8px;border:1px solid #42526c;background:#182438;color:inherit}button{cursor:pointer}form,.tools{display:flex;gap:10px;flex-wrap:wrap}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:15px;margin:25px 0}.card{background:#182438;padding:20px;border-radius:12px}.card b{display:block;font-size:30px;color:#82e5bf}.table{overflow:auto}table{width:100%;border-collapse:collapse;white-space:nowrap}td,th{text-align:left;padding:13px;border-bottom:1px solid #29374e}th{color:#a9b8ce}.muted{color:#a9b8ce}.online{color:#82e5bf}#message{min-height:24px;color:#f2bb75}[hidden]{display:none!important}</style><main>
<h1>EMBERFALL · 遊玩後台</h1><p class="muted">IP 不等於一個人；同一所學校可能共用 IP。人數是匿名裝置數，清除儲存或換裝置會另計。僅包含開啟統計的玩家。</p>
<form id="login"><input id="token" type="password" autocomplete="off" placeholder="管理員密鑰 / Admin token" required minlength="24" aria-label="管理員密鑰"><button>登入 / Sign in</button></form>
<p id="message" role="status"></p><section id="dashboard" hidden><div class="tools"><select id="days" aria-label="時間範圍"><option value="1">最近 24 小時</option><option value="7" selected>最近 7 天</option><option value="30">最近 30 天</option></select><button id="refresh">重新整理</button><button id="logout">登出</button><span id="updated" class="muted"></span></div><div id="cards" class="cards"></div><p class="muted">每 15 秒更新。在線＝前 60 秒有心跳、遊戲可見且最近 2 分鐘有操作。時長＝活躍遊玩時間；斷線的結束時間是最後心跳估計，最多漏記 20 秒。</p><div class="table"><table><thead><tr><th>狀態</th><th>匿名玩家</th><th>IP</th><th>開始</th><th>結束 / 最後活動</th><th>活躍時長</th><th>種族 / 職業</th><th>層數</th></tr></thead><tbody id="rows"></tbody></table></div><div class="tools"><button id="prev">上一頁</button><span id="pageLabel"></span><button id="next">下一頁</button></div></section></main><script>
let secret='',page=0,busy=false;const $=id=>document.getElementById(id);const date=n=>new Date(n).toLocaleString();const duration=ms=>{const n=Math.floor(ms/1000);return Math.floor(n/3600)+'h '+Math.floor(n%3600/60)+'m '+n%60+'s'};
async function load(){if(!secret||busy)return;busy=true;const credential=secret;try{const res=await fetch('/api/stats?days='+$('days').value+'&page='+page,{headers:{Authorization:'Bearer '+secret}});if(res.status===401){logout();throw Error('密鑰不正確 / Invalid token');}if(!res.ok)throw Error('讀取失敗 / Request failed');const data=await res.json();if(secret!==credential)return;$('login').hidden=true;$('dashboard').hidden=false;$('message').textContent='';$('cards').replaceChildren();for(const [label,value] of [['匿名玩家',data.summary.players],['目前在線',data.online],['遊玩場次',data.summary.sessions],['不同 IP',data.summary.ips],['總活躍時間',duration(data.summary.active_ms)]]){const card=document.createElement('div');card.className='card';const b=document.createElement('b');b.textContent=value;card.append(b,document.createTextNode(label));$('cards').append(card);}
$('rows').replaceChildren();for(const row of data.rows){const online=!row.ended&&row.active&&data.now-row.last_seen<60000;const tr=document.createElement('tr');for(const value of [online?'● 在線':row.ended?'已離開':'離線 / 閒置',row.visitor.slice(0,8),row.ip,date(row.started),date(row.ended||row.last_seen)+(row.ended?'':'（最後心跳）'),duration(row.active_ms),row.race+' / '+row.job,row.floor]){const td=document.createElement('td');td.textContent=value;tr.append(td);}if(online)tr.firstChild.className='online';$('rows').append(tr);}$('prev').disabled=page===0;$('next').disabled=(page+1)*100>=data.summary.sessions;$('pageLabel').textContent='第 '+(page+1)+' 頁';$('updated').textContent='更新於 '+date(data.now);
}catch(error){$('message').textContent=error.message;}finally{busy=false;}}
function logout(){secret='';$('token').value='';$('dashboard').hidden=true;$('login').hidden=false;$('rows').replaceChildren();$('cards').replaceChildren();}
$('login').onsubmit=event=>{event.preventDefault();secret=$('token').value;$('token').value='';page=0;load();};$('logout').onclick=logout;$('refresh').onclick=load;$('days').onchange=()=>{page=0;load();};$('prev').onclick=()=>{page--;load();};$('next').onclick=()=>{page++;load();};setInterval(load,15000);
</script></html>`;
