'use strict';
const fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'..'),html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const script=[...html.matchAll(/<script defer src="([^"]+)"><\/script>/g)].map(m=>fs.readFileSync(path.join(root,m[1]),'utf8')).join('\n');
const core=script.split('const MOVE_KEYS=')[0];
const stubs=`const nodes=new Map(),noop=()=>{},ctxStub=new Proxy({}, {get:(o,k)=>o[k]||noop,set:(o,k,v)=>(o[k]=v,true)});const document={getElementById(id){if(!nodes.has(id))nodes.set(id,{style:{},classList:{add:noop,remove:noop,toggle:noop},getContext:()=>ctxStub,focus:noop,innerHTML:'',textContent:'',insertAdjacentHTML(where,html){this.innerHTML+=html}});return nodes.get(id)},querySelectorAll:()=>[]};const storage=new Map(),localStorage={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)};`;
const tests=`let checks=0;function assert(x,m){if(!x)throw Error(m);checks++}function reject(fn,m){let bad=false;try{fn()}catch{bad=true}assert(bad,m)}
assert(Object.values(RACE_POLICIES).reduce((n,r)=>n+r.jobs.length,0)===77,'77 builds');
for(const r of Object.keys(RACES))for(const j of DUO_CLASSES){if(!classAllowed(r,j)){reject(()=>createState(r,j,'classic','duo'),'restriction');continue}createState(r,j,'classic','duo');assert(validate(s),'initial '+r+j);assert(validate(JSON.parse(JSON.stringify(s))),'roundtrip');update();assert($('skills').innerHTML.includes('duoWorkshop'),'UI');assert(SPECIALIZATIONS[j].length===2,'specializations')}
function arena(j,r='human'){createState(r,j,'classic','duo-arena');view='';const f=level();f.map=Array(W*H).fill(0);f.objects=[];f.enemies=[];f.allies=[];f.env=[];f.visible.fill(true);s.p.x=10;s.p.y=10;s.p.face={x:1,y:0};s.p.shield=100;return f}
let f=arena('oath');assert(skill(3),'guard ability');assert(s.p.duo.pool===10&&s.p.cooldowns[3]===6,'guard costs');let snap=JSON.stringify(s);assert(!skill(3)&&JSON.stringify(s)===snap,'cooldown free');let resolve=s.p.duo.pool;hurt(10,'enemy');assert(s.p.duo.pool===resolve+5,'blocked damage earns resolve');s.p.duo.pool=100;hurt(10,'enemy');assert(s.p.duo.pool===100,'resolve cap');
f=arena('oath');s.p.duo.oath='revenge';snap=JSON.stringify(s);assert(!skill(3)&&JSON.stringify(s)===snap,'missing target free');let e=makeEnemy('rat',{x:11,y:10});e.hp=e.maxHp=200;f.enemies=[e];visibility();assert(skill(3)&&e.hp<200,'vengeance damage');
f=arena('oath');s.p.duo.oath='mercy';s.p.hp-=20;s.p.status.poison=5;assert(skill(3),'mercy');assert(!s.p.status.poison&&s.p.hp===s.p.maxHp&&s.p.duo.pool===18,'mercy heal cleanse resolve');
f=arena('oath','demon');s.p.duo.oath='broken';s.p.hp=6;f.enemies=[makeEnemy('rat',{x:11,y:10})];visibility();snap=JSON.stringify(s);assert(!skill(3)&&JSON.stringify(s)===snap,'no suicidal judgment');
f=arena('oath','angel');duoMenu();snap=JSON.stringify(s);assert(!duoSetOath('revenge')&&JSON.stringify(s)===snap,'angel oath constraint');assert(duoSetOath('mercy'),'angel mercy');
f=arena('oath','demon');duoMenu();snap=JSON.stringify(s);assert(!duoSetOath('mercy')&&JSON.stringify(s)===snap,'demon oath constraint');assert(duoSetOath('broken')&&s.p.duo.pool===0,'oathbreak');s.p.duo.pool=20;duoMenu();assert(duoSetOath('guard'),'renew after break');
f=arena('machinist');e=makeEnemy('sentinel',{x:14,y:10});e.hp=e.maxHp=200;f.enemies=[e];visibility();assert(skill(3),'turret deployed');assert(f.devices[0].ttl===20&&s.p.duo.pool===3&&s.p.mp===22&&s.p.cooldowns[3]===4,'turret cost duration');assert(e.hp<200,'turret shoots');assert(validate(s),'device save');for(let n=0;n<20;n++)alliesTurn();assert(!f.devices.length,'device expires');
f=arena('machinist');f.map[key(11,10)]=1;snap=JSON.stringify(s);assert(!skill(3)&&JSON.stringify(s)===snap,'blocked deployment free');
f=arena('machinist');s.p.duo.pool=0;snap=JSON.stringify(s);assert(!skill(3)&&JSON.stringify(s)===snap,'parts required');
f=arena('machinist');duoMenu();assert(duoWorkshop('trap'),'trap placement');e=makeEnemy('rat',{x:11,y:10});e.hp=e.maxHp=100;f.enemies=[e];alliesTurn();assert(e.hp===77&&e.freeze===2&&!f.devices.length,'trap damage and consumed');
f=arena('machinist');duoMenu();assert(duoWorkshop('assistant'),'assistant');assert(f.allies[0].mechanical&&f.allies[0].ttl===35,'assistant duration');s.p.duo.pool=12;duoMenu();assert(duoWorkshop('assistant'),'second assistant');duoMenu();snap=JSON.stringify(s);assert(!duoWorkshop('assistant')&&JSON.stringify(s)===snap,'shared ally cap');close();travel('main-2','down');assert(level().allies.length===2&&level().allies.every(a=>a.mechanical),'assistants travel');assert(validate(s),'assistant save');
f=arena('machinist','construct');s.p.hp-=30;duoMenu();assert(duoWorkshop('repair')&&s.p.hp===s.p.maxHp-6,'construct repairs');
f=arena('machinist');let i=item('sword',0,{known:true,cursed:false});addItem(i,false);duoMenu();assert(duoWorkshop('dismantle',i.id)&&s.p.duo.pool===7&&!s.p.inventory.includes(i),'dismantle');duoMenu();snap=JSON.stringify(s);assert(!duoWorkshop('dismantle',s.p.equipment.weapon)&&JSON.stringify(s)===snap,'equipped protected');
f=arena('machinist');assert(skill(3),'device for travel');close();travel('main-2','down');assert(s.floors['main-1'].devices.length===1&&!level().devices?.length,'devices stay');
for(const j of DUO_CLASSES)for(let mask=0;mask<8;mask++){arena(j);duoStory();snap=JSON.stringify(s);assert(!duoChoose(0,0)&&JSON.stringify(s)===snap,'story locked by depth');close();s.stats.deepest=20;for(let n=0;n<3;n++){duoStory();assert(duoChoose(n,mask>>n&1),'chapter choice');duoStory();snap=JSON.stringify(s);assert(!duoChoose(n,0)&&JSON.stringify(s)===snap,'no duplicate reward');close()}assert(validate(s),'story save');assert(duoEnding().length>0,'epilogue');endScreen();assert($('modal').innerHTML.includes('職業後日談'),'ending visible');view=''}
arena('oath');let bad=JSON.parse(JSON.stringify(s));bad.p.duo.pool=101;reject(()=>validate(bad),'bad pool');arena('machinist');bad=JSON.parse(JSON.stringify(s));bad.floors[bad.floor].devices=[{x:100,y:1,ttl:20,type:'turret'}];reject(()=>validate(bad),'bad device');
arena('machinist');s.status='dead';snap=JSON.stringify(s);assert(!skill(3)&&!classAction(8)&&JSON.stringify(s)===snap,'dead locked');return checks;`;
console.log('Duo classes: '+new Function(stubs+core+tests)()+' checks passed');
const locale=script.slice(script.indexOf('const LANGUAGE_KEY='),script.indexOf('let LANGUAGE_CHOICE='));
const pairs=script.slice(script.indexOf('for(const [zh,en]of'),script.indexOf('const EN_RE='));
const trans=script.slice(script.indexOf('const EN_RE='),script.indexOf('const localText='));
console.log('Duo English: '+new Function(stubs+core+locale+pairs+"let LANGUAGE='en';duoTranslations();"+trans+`duoTranslations();let checks=0;for(const pair of DUO_TEXT){if(t(pair[0])!==pair[1])throw Error('Translation '+pair[0]);checks++}for(const j of DUO_CLASSES){createState('human',j,'classic','english');view='';duoMenu();if(/[\\u3400-\\u9fff]/.test(englishText($('modal').innerHTML)))throw Error('Untranslated menu');close();duoStory();if(/[\\u3400-\\u9fff]/.test(englishText($('modal').innerHTML)))throw Error('Untranslated story');close();checks+=2}return checks;`)()+' checks passed');
