'use strict';
// Run: node tests/narrative.cjs
const fs=require('node:fs'),path=require('node:path');
const html=fs.readFileSync(path.join(__dirname,'..','index.html'),'utf8');
const script=[...html.matchAll(/<script defer src="([^"]+)"><\/script>/g)].map(m=>fs.readFileSync(path.join(__dirname,'..',m[1]),'utf8')).join('\n');
new Function(script);
const core=script.split('const MOVE_KEYS=')[0];
const stubs=`const nodes=new Map(),noop=()=>{};const stubContext=new Proxy({},{get:(o,k)=>o[k]||noop});const document={getElementById(id){if(!nodes.has(id))nodes.set(id,{style:{},classList:{add:noop,remove:noop,toggle:noop},getContext:()=>stubContext,focus:noop,innerHTML:'',textContent:''});return nodes.get(id)},querySelectorAll:()=>[]};const storage=new Map();const localStorage={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)};`;
const tests=`
let checks=0;function assert(x,label){if(!x)throw Error(label);checks++}function reject(fn,label){let bad=false;try{fn()}catch{bad=true}assert(bad,label)}
function ready(base,id,stage){s=JSON.parse(base);plotState();for(const t of Object.keys(PLOT_THREADS))s.plot.choices[t]=Array(stage).fill(2);s.plot.choices[id]=Array(stage).fill(2);s.plot.evidence=Object.keys(PLOT_THREADS).flatMap(t=>[0,1,2,3].map(i=>t+':'+i));s.p.gold=500;s.p.maxMp=s.p.mp=100;s.p.hunger=1000;s.p.x=10;s.p.y=10;s.p.shield=0;if(s.p.ascendant)s.p.ascendant.resource=100;if(s.p.classState)s.p.classState.pool=4;
const n=PLOT_THREADS[id].floors[stage],f={...s.floors['main-1'],...floorMeta('main-'+n),map:Array(W*H).fill(0),enemies:[],objects:[{x:11,y:10,type:'plotNpc',thread:id,stage,used:false}],allies:[],env:[],bossDead:true,plotReady:true,start:{x:10,y:10},end:{x:20,y:10}};s.floors={[f.id]:f};s.floor=f.id;s.rng=rngState;view='narrative';return f}
let combinations=0;
for(const race of Object.keys(RACES))for(const job of Object.keys(JOBS)){if(!classAllowed(race,job))continue;combinations++;createState(race,job,'classic','identity-'+race+job);const base=JSON.stringify(s);
for(const id of Object.keys(PLOT_THREADS))for(let stage=0;stage<4;stage++){
 for(const kind of ['race','job']){ready(base,id,stage);const turn=s.turn;assert(plotInvestigate(id,stage,kind),'identity action '+race+job+id+stage+kind);assert(s.turn===turn+1,'investigation one turn');view='narrative';const snapshot=JSON.stringify(s);assert(!plotInvestigate(id,stage,kind)&&JSON.stringify(s)===snapshot,'investigation cannot repeat');assert(validate(s),'identity save')}
 for(let i=0;i<3;i++){ready(base,id,stage);if(id==='city'&&stage===2)s.plot.choices.dead=[0,2];if(id==='knight'&&stage===2)s.plot.choices.knight=[0,2];const before=s.turn;assert(plotChoose(id,stage,i),'choice '+race+job+id+stage+i);assert(s.plot.choices[id][stage]===i&&s.turn===before+1,'choice commits one turn');const snapshot=JSON.stringify(s);assert(!plotChoose(id,stage,i)&&JSON.stringify(s)===snapshot,'choice replay rejected');assert(validate(JSON.parse(snapshot)),'choice save roundtrip')}
}}
assert(combinations===60,'all legal identities');
createState('human','warden','classic','locks');let base=JSON.stringify(s);ready(base,'city',0);s.plot.evidence=[];assert(plotSceneGate('city',0,PLOT_CHAPTERS.city[0].choices[2])==='','warden repair alternative');ready(base,'dead',0);s.plot.evidence=[];let before=JSON.stringify(s);assert(!plotChoose('dead',0,2)&&JSON.stringify(s)===before,'missing evidence free');ready(base,'city',1);s.p.mp=0;before=JSON.stringify(s);assert(!plotChoose('city',1,2)&&JSON.stringify(s)===before,'unaffordable free');ready(base,'city',2);s.plot.choices.dead=[0,1];assert(plotSceneGate('city',2,PLOT_CHAPTERS.city[2].choices[2])!=='','cross thread testimony gate');ready(base,'knight',2);s.plot.choices.knight=[0,1];assert(plotSceneGate('knight',2,PLOT_CHAPTERS.knight[2].choices[2])!=='','farewell prerequisite');ready(base,'wound',3);s.plot.evidence=['wound:3'];assert(plotSceneGate('wound',3,PLOT_CHAPTERS.wound[3].choices[2])!=='','eight clue gate');
ready(base,'city',0);level().objects=[];before=JSON.stringify(s);assert(!plotChoose('city',0,0)&&JSON.stringify(s)===before,'remote choice denied');ready(base,'city',1);s.plot.choices.city=[];before=JSON.stringify(s);assert(!plotChoose('city',1,0)&&JSON.stringify(s)===before,'out of order denied');ready(base,'city',0);s.status='dead';before=JSON.stringify(s);assert(!plotChoose('city',0,0)&&JSON.stringify(s)===before,'dead decision denied');
ready(base,'city',0);s.plot.evidence=[];const o={x:11,y:10,type:'plotClue',thread:'city',stage:0,used:false};level().objects.push(o);let turn=s.turn;assert(plotRead(o)&&plotHasClue('city',0)&&s.turn===turn,'clue read free');assert(plotRead(o)&&s.plot.evidence.length===1,'clue unique');s.p.x=20;assert(!plotRead(o),'remote clue denied');
ready(base,'city',0);let trust=s.plot.trust.city;recordPlotTalk('city',0,'evidence');recordPlotTalk('city',0,'evidence');assert(s.plot.trust.city===trust+2,'evidence trust once');plotDialogue('city',0,'past');assert($('modal').innerHTML.includes(PLOT_CHAPTERS.city[0].past.zh),'authored dialogue');let copy=JSON.parse(JSON.stringify(s));restore(copy);assert(s.plot.talks.includes('city:0:past'),'dialogue persists');
for(const option of [0,1,2]){ready(base,'city',1);s.plot.choices.city=[option];const f=level(),hp=s.p.hp,gold=s.p.gold,count=countItem('food');plotConsequences(f);if(option===0)assert(countItem('food')===count+1,'promise supplies');if(option===1)assert(f.enemies.length===1,'promise pursuer');if(option===2)assert(s.p.shield===12,'promise shield');const snapshot=JSON.stringify(s);plotConsequences(f);assert(JSON.stringify(s)===snapshot,'consequence once')}
ready(base,'dead',2);s.plot.choices.city=[0,0,0];s.plot.choices.dead=[0,0];s.p.mp=0;plotConsequences(level());assert(s.p.mp===0,'council removes scribe support');
for(const ending of Object.keys(PLOT_ENDINGS)){createState('human','spirit','classic','ending-'+ending);generateFloor('main-24');s.floor='main-24';const f=level();f.enemies=[];f.env=[];f.bossDead=true;f.objects=f.objects.filter(o=>o.type==='heart');s.p.x=f.end.x;s.p.y=f.end.y;s.p.hp=s.p.maxHp;s.p.mp=s.p.maxMp;s.plot.evidence=Object.keys(PLOT_THREADS).flatMap(t=>[0,1,2,3].map(i=>t+':'+i));for(const id of Object.keys(PLOT_THREADS))s.plot.choices[id]=[2,2,2,2];if(ending==='release')s.plot.choices.dead[3]=0;if(ending==='dominion')s.plot.choices.pact[3]=0;
assert(plotEndingGate(ending),'ending unlock '+ending);view='plotFinal';assert(plotStartFinale(ending)&&s.status==='playing'&&!f.bossDead,'ending battle '+ending);const enemy=f.enemies.find(e=>e.id===s.plot.finalBoss);assert(enemy.type===PLOT_ENDINGS[ending].boss,'unique ending guardian');assert(f.env.some(e=>e.type===PLOT_ENDINGS[ending].terrain),'different battlefield');view='plotFinal';assert(!plotFinish(),'victory cannot bypass boss');assert(validate(s),'pending finale save');enemy.hp=0;killEnemy(enemy);plotFinalMenu();assert(plotFinish()&&s.status==='won'&&s.plot.ending===ending,'ending confirmed');assert($('modal').innerHTML.includes(PLOT_ENDINGS[ending].name.zh)&&$('modal').innerHTML.includes('角色後日談'),'ending epilogues');assert(validate(JSON.parse(JSON.stringify(s))),'won ending save')}
createState('human','warden','classic','locked-endings');assert(plotEndingGate('seal')&&!plotEndingGate('restore')&&!plotEndingGate('release')&&!plotEndingGate('dominion'),'ending availability');const old=JSON.parse(JSON.stringify(s));delete old.plot;for(const f of Object.values(old.floors)){f.objects=f.objects.filter(o=>!o.type.startsWith('plot'));delete f.plotReady}assert(validate(old),'old save accepted');restore(old);assert(s.plot&&level().objects.some(o=>o.type==='plotNpc'),'old floors gain scenes');let bad=JSON.parse(JSON.stringify(s));bad.plot=null;reject(()=>validate(bad),'invalid plot');bad=JSON.parse(JSON.stringify(s));bad.plot.choices.city=[7];reject(()=>validate(bad),'invalid choice');bad=JSON.parse(JSON.stringify(s));bad.plot.evidence=['city:0','city:0'];reject(()=>validate(bad),'duplicate evidence');bad=JSON.parse(JSON.stringify(s));bad.floors[bad.floor].objects.find(o=>o.type==='plotNpc').stage=3;reject(()=>validate(bad),'misplaced plot object');
createState('human','warden','explorer','academy',true);assert(!level().objects.some(o=>o.type.startsWith('plot')),'training unchanged');view='narrative';before=JSON.stringify(s);assert(!plotChoose('city',0,0)&&JSON.stringify(s)===before,'training no choices');
createState('human','warden','classic','all-scenes');for(let n=2;n<=24;n++)generateFloor('main-'+n);assert(Object.values(s.floors).flatMap(f=>f.objects).filter(o=>o.type==='plotNpc').length===20,'twenty world scenes');for(const f of Object.values(s.floors)){s.floor=f.id;s.p.x=f.start.x;s.p.y=f.start.y;for(const o of f.objects.filter(o=>['plotNpc','plotClue'].includes(o.type)))assert(pathStep(f.start,o,{doors:true})||distance(f.start,o)===0,'scene reachable');}assert(validate(s),'whole narrative world valid');
return checks;
`;
console.log('Narrative behavior: '+new Function(stubs+core+tests)()+' checks passed');
const locale=script.slice(script.indexOf('const LANGUAGE_KEY='),script.indexOf('let LANGUAGE_CHOICE='));
const pairs=script.slice(script.indexOf('for(const [zh,en]of'),script.indexOf('const EN_RE='));
const trans=script.slice(script.indexOf('const EN_RE='),script.indexOf('const localText='));
const languageTests=`let count=0;const inspect=o=>{if(!o||typeof o!=='object')return;if(o.zh&&o.en){if(englishText(o.zh)!==o.en)throw Error('Translation: '+o.zh);count++}else Object.values(o).forEach(inspect)};[PLOT_THREADS,PLOT_CHAPTERS,PLOT_RACES,PLOT_JOBS,PLOT_COMBOS,PLOT_ENDINGS,PLOT_BOSS_LINES,PLOT_FUTURES].forEach(inspect);createState('demon','spirit','classic','english-story');plotDialogue('city',0,'race');if(/[\\u3400-\\u9fff]/.test(englishText($('modal').innerHTML)))throw Error('Untranslated dialogue: '+englishText($('modal').innerHTML).match(/[\\u3400-\\u9fff]+/g));return count;`;
console.log('Narrative translation: '+new Function(stubs+core+locale+pairs+"let LANGUAGE='en';"+trans+languageTests)()+' bilingual passages passed');
